export const FETCH_POST_DATA_SUCCESS = 'blogPost/FETCH_POST_DATA_SUCCESS';
export const FETCH_POST_DATA_REQUEST = 'blogPost/FETCH_POST_DATA_REQUEST';
export const FETCH_POST_DATA_FAILURE = 'blogPost/FETCH_POST_DATA_FAILURE';
